Projektbeschreibung von München Transparent aktualisieren und übersetzen
okfde/2013.archiv.codefor.de pull request #671
Opened 2016-11-16 20:34 UTC by konstin

Ich hoffe, dass das Format der Übersetzung so passt. Ansonsten habe ich einige Kleinigkeiten zu München Transparent korrigiert.

2016-11-16 22:48 UTC, johnjohndoe requested changes

2016-11-16 22:48 UTC, johnjohndoe commented on en/projekte/2014-07-14-Muenchen-Transparent.html
> +München Transparent does not only want to deliver data, but also explain the procedures in municipal politics. Therefore, there's a coprehensive glossary besides video explaining the way an initative
~~bevor~~ before

2016-11-16 22:48 UTC, johnjohndoe commented on en/projekte/2014-07-14-Muenchen-Transparent.html
> +München Transparent does not only want to deliver data, but also explain the procedures in municipal politics. Therefore, there's a coprehensive glossary besides video explaining the way an initative
~~protocolls~~ protocols

2016-11-16 22:48 UTC, johnjohndoe commented on en/projekte/2014-07-14-Muenchen-Transparent.html
> +München Transparent does not only want to deliver data, but also explain the procedures in municipal politics. Therefore, there's a coprehensive glossary besides video explaining the way an initative
You could add a link to the OParl-API project.

2016-11-16 22:48 UTC, johnjohndoe commented on en/projekte/2014-07-14-Muenchen-Transparent.html
> +München Transparent does not only want to deliver data, but also explain the procedures in municipal politics. Therefore, there's a coprehensive glossary besides video explaining the way an initative
~~ist Open Source (The Source Code is available on GitHub)~~
is open source (the source code is available on GitHub)

2016-11-16 22:54 UTC, johnjohndoe commented on en/projekte/2014-07-14-Muenchen-Transparent.html
> +München Transparent does not only want to deliver data, but also explain the procedures in municipal politics. Therefore, there's a coprehensive glossary besides video explaining the way an initative
~~plattform~~ platform

2016-11-17 09:31 UTC, konstin commented on en/projekte/2014-07-14-Muenchen-Transparent.html
> +München Transparent does not only want to deliver data, but also explain the procedures in municipal politics. Therefore, there's a coprehensive glossary besides video explaining the way an initative
Fixed.

2016-12-21 20:35 UTC, konstin commented
@johnjohndoe @arduina: Wie sieht's denn im Moment aus mit den Übersetzungen?

2017-01-02 12:21 UTC, merged